export const metadata = {
  title: "Terms & Conditions | PromptSelz",
  description: "Review the terms and conditions for using PromptSelz, including responsibilities, content usage, and disclaimers.",
};

export default function TermsPage() {
  return (
    <section className="bg-slate-950 text-slate-100 px-4 py-14 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-5xl space-y-10">
        <div>
          <p className="inline-flex rounded-full bg-cyan-500/20 px-3 py-1 text-sm font-semibold text-cyan-200">
            Terms & Conditions
          </p>
          <h1 className="mt-6 text-4xl font-semibold tracking-tight text-white sm:text-5xl">
            Terms of use for PromptSelz services and marketplace access.
          </h1>
          <p className="mt-6 text-lg leading-8 text-slate-300">
            These terms provide a clear overview of what’s expected from users, how content can be used, and important disclaimers.
          </p>
        </div>

        <div className="space-y-10 rounded-3xl border border-slate-800 bg-slate-900/80 p-8 shadow-xl shadow-slate-950/30">
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">User responsibilities</h2>
            <p className="text-slate-300 leading-7">
              As a user of PromptSelz, you agree to use the platform in accordance with applicable laws and not submit abusive,
              harmful, or infringing content. You are responsible for any information you provide and the way you use prompt materials.
            </p>
            <p className="text-slate-300 leading-7">
              You should review prompt content before applying it in any context and ensure it is appropriate for your needs.
              PromptSelz does not assume responsibility for how third-party AI tools may interpret or act on shared prompts.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">Content usage</h2>
            <p className="text-slate-300 leading-7">
              All prompt content on PromptSelz is provided for informational and creative use. You may use prompts for personal
              and commercial applications, but you are responsible for complying with any third-party terms tied to AI platforms.
            </p>
            <p className="text-slate-300 leading-7">
              PromptSelz does not guarantee results or endorse any specific output generated by third-party AI services.
              Content may be updated or removed to maintain marketplace quality and compliance.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">Disclaimer</h2>
            <p className="text-slate-300 leading-7">
              PromptSelz is provided "as is" without warranties of any kind. We do not guarantee the accuracy,
              reliability, or suitability of any prompts, and we are not liable for any damages arising from your use of the platform.
            </p>
            <p className="text-slate-300 leading-7">
              By using PromptSelz, you acknowledge that AI-generated output may vary and that you are responsible for reviewing
              and adapting content as needed for your own use case.
            </p>
          </section>
        </div>
      </div>
    </section>
  );
}
